import { I18nManager } from "react-native";
import * as colors from './colors';

export const themeLight = {
  dark: false,
  colors: {
    StatusbarStyle: 'dark-content',
    StatusbarColor: '#fff',
    white: "#fff",
    primary: "#FF0004",
    primaryLight: "#FF657E",
    secondary: "#2680EB",
    primaryDarkRed: "#D92648",
    background: '#FFFFFF',
    inputtextbackground: '#e5e5e560',
    background2: "#F6F6F6",
    overlay: '#FFFFFF',
    poppins: I18nManager.isRTL ? "JFFlat-Regular" : "Poppins-Medium",
    poppinsbold: I18nManager.isRTL ? "JFFlat-Regular" : "Poppins-SemiBold",


    mainText: colors.black,
    secondText: colors.gray10,
    textborder: colors.gray4,
    textcolor: colors.gray6,
    icon: '#949494',

    textTab: "#949494",
    textTabFocus: "#FF0004",

    home_primary: "#FF0004",
    home_primaryLight: "#FF657E",
    searchboxbackground: "#e5e5e560",
    chatbackground: "#e5e5e550",

    card: colors.white,
    text: colors.gray7,
    border: colors.gray2,
    success: colors.green,
    warning: colors.yellow,
    error: colors.red,
    secondaryText: colors.gray6,
    thirdText: colors.gray4,
    forthText: colors.gray6,
    fifthText: colors.gray4,
    secondaryIcon: colors.gray2,
    secondaryButton: colors.gray1,
    secondaryCard: colors.white,
    secondaryBackground: colors.white,
    thirdCard: colors.gray3,
    modal: colors.gray7,
    textButtonGroup: colors.gray4,
  },
};

export const themeDark = {
  dark: true,
  colors: {
    StatusbarStyle: 'light-content',
    StatusbarColor: '#212121',
    white: "#fff",
    primary: "#fff",
    primaryLight: "#FF657E",
    secondary: "#2680EB",
    primaryDarkRed: "#D92648",
    background: '#121212',
    inputtextbackground: '#212121',
    overlay: '#212121',
    background2: '#212121',
    poppins: I18nManager.isRTL ? "JFFlat-Regular" : "Poppins-Medium",
    poppinsbold: I18nManager.isRTL ? "JFFlat-Regular" : "Poppins-SemiBold",

    mainText: '#FFFFFF',
    secondText: '#BEBEBE',
    textborder: colors.gray4,
    textcolor: colors.gray6,
    icon: '#949494',

    textTab: "#949494",
    textTabFocus: "#fff",

    home_primary: "#383838",
    home_primaryLight: "#707070",
    searchboxbackground: "#121212",
    chatbackground: "#212121",

    card: colors.gray13,
    text: colors.gray8,
    border: colors.gray13,
    success: colors.green,
    warning: colors.yellow,
    error: colors.red,
    secondaryText: colors.gray10,
    thirdText: colors.gray9,
    forthText: colors.gray9,
    fifthText: colors.gray10,
    secondaryButton: colors.gray12,
    secondaryIcon: colors.gray10,
    secondaryCard: colors.gray11,
    secondaryBackground: colors.gray12,
    thirdCard: colors.gray11,
    modal: colors.gray12,
    textButtonGroup: colors.gray8,
  },
};
